theme: jekyll-theme-slate
lsi: false
safe: true
source: []
incremental: false
highlighter: rouge
url: binarycrown.github.io
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
